name: spring-ci

on:
  pull_request:
    branches:
      - "dev"
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Execute Permission for gradlew
        run: |
          chmod +x gradlew
        shell: bash

      - name: Make yml file
        run: |
          cd ./src/main/resources
          rm -rf ./application.yml
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        shell: bash

      - name: Build gradle
        run: |
          ./gradlew clean build
        shell: bash

      
