name: test-every-push

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@4
        with:
          distribution: temurin
          java-version: 17

     
          